services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    # volumes:
    #   - ./data:/data/db

  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8093:8081
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin